/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.homesoft.dcp;

import org.junit.Test;
import static org.junit.Assert.*;

public class SampleTest {
    @Test public void testAppHasAGreeting() {
        Sample classUnderTest = new Sample();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
